org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false

# Mod info
mod_version=Release 1.0
maven_group=fever.visual
archives_base_name=fevervisual

# Minecraft / Fabric
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
fabric_version=0.141.4+1.21.11

# Media Player Info
mediaplayer_version=0.1.0
